project:
  type: book

book:
  title: "Data Science Worklows in R"
  subtitle: "An introduction to deploying production quality R code"
  author: "Dean Marchiori"
  date: "2024"
  cover-image: img/cover.png
  chapters:
    - index.qmd
    - chapters/01-setup.qmd  
    - chapters/02-data_analysis_workflows.qmd  
    - chapters/03-experimentation.qmd  
    - chapters/04-what_is_production.qmd   
    - chapters/05-elements_of_prod_code.qmd
    - chapters/06-practical_considerations.qmd
    - chapters/07-case_study.qmd  
    - chapters/resources.qmd  
    - chapters/acknowledgements.qmd  
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt  
  epub: 
    toc: true

editor: source

