project:
  type: book

book:
  title: "Data Science Workflows in R"
  subtitle: "An introduction to deploying production quality R code"
  author: "Dean Marchiori"
  date: today
  cover-image: img/cover.png
  chapters:
    - index.qmd
    - chapters/setup.qmd  
    - chapters/data_analysis_workflows.qmd  
    - chapters/r_code_workflows.qmd
    - chapters/development.qmd  
    - chapters/what_is_production.qmd   
    - chapters/elements_of_prod_code.qmd
    - chapters/practical_considerations.qmd
    - chapters/case_study.qmd  
    - chapters/resources.qmd  
    - chapters/acknowledgements.qmd  
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt  
  epub: 
    toc: true

editor: source

nocite: |
  @*